#!/usr/bin/env bash

set -e

# Determine the script directory
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Set the root directory to your home directory and the repository name
ROOTDIR="${HOME}/simple_shell"

set -x

# See also ".mailmap" for how email addresses and names are deduplicated
cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File @generated by generate-authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See generate-authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
